services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb    
    environment:
      POSTGRES_DB: seatsnag
      POSTGRES_USER: seatsnag
      POSTGRES_PASSWORD: seatsnag
    ports:
      - "5432:5432"